# Generated by Django 5.1.6 on 2025-02-25 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=15)),
                ('payment_type', models.CharField(choices=[('Payment', 'Payment'), ('Fine', 'Fine')], max_length=15)),
                ('session_url', models.URLField()),
                ('session_id', models.IntegerField()),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrowing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowing.borrowing')),
            ],
        ),
    ]
