# Generated by Django 5.1.6 on 2025-02-26 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('borrowing', '0002_alter_borrowing_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='book',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='book.book'),
        ),
    ]
